name: Docs

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Requirements
        run: |
          pip3 install -r requirements.txt
          sudo apt-get install doxygen
      - name: Build docs
        run: |
          cd docs
          make html
          touch _build/html/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages  # The branch the action should deploy to.
          folder: docs/_build/html  # The folder the action should deploy.
